# ANN in Python

## Artificial Neuron in Python

In [10]:
# 연산
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))
b  = 1
out = 1 if x1+x2>=b else 0
print('뉴런 출력:', out)

입력(콤마로 구분하여 입력하시오): 0,1
뉴런 출력: 1


0, 0

## Hebb's artificial neuron
햅의 이론
 - 학습이 이루어지면 시냅스가 강화된다.
 - 시냅스의 변화를 "가중치(weight)로 모델링
햅의 인공 신경 세포(artificial neuron)

In [14]:
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))

b = -0.5
w1 = 0.38
w2 = 0.42
 
y = x1*w1 + x2*w2 + b

out= 1 if y >= 0.0 else 0

print('뉴런 출력:', out)

입력(콤마로 구분하여 입력하시오): 0,1
뉴런 출력: 0


In [16]:
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))

b = -0.01
w1 = 0.36
w2 = 0.39
 
y = x1*w1 + x2*w2 + b

out= 1 if y >= 0.0 else 0

print('뉴런 출력:', out)

입력(콤마로 구분하여 입력하시오): 0,1
뉴런 출력: 1


In [20]:
import numpy as np

# 연산
x1, x2 = eval( input('입력(콤마로 구분하여 입력하시오): '))
x  = np.array([x1, x2])

b = -0.5
w1 = 0.38  
w2 = 0.42
W = np.array([w1, w2]).reshape(-1,1)

y = np.dot(x,W) + b     #행렬 곱샘 x*W

out= 1 if y >= 0.0 else 0

print('W 출력:', W)
print('y 출력:', y)
print('뉴런 출력:', out)

입력(콤마로 구분하여 입력하시오): 1,0
W 출력: [[0.38]
 [0.42]]
y 출력: [-0.12]
뉴런 출력: 0


In [27]:
x = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
#t = np.array([0., 1., 1., 1.] ).reshape(-1,1)
t = np.array([0., 0., 0., 1.] ).reshape(-1,1)
b = -0.5
w1 = 0.38  
w2 = 0.42
W = np.array([w1, w2]).reshape(-1,1)
 
y = np.dot(x,W) + b  #matrix multiplication

print("y:\n",y, y.shape)

out =  (y>=0.0).astype(int)     #step fuctino
print('out:\n',out)

e = t - y       # 로젠블라트 방법(SLP)
#e = t - out     # 역전파학습(MLP) error back propagation 
print('error:\n', e)            #실제값(t)과 예측한값(y)의 차이

# t-out 는 빠르지만 


y:
 [[-0.5 ]
 [-0.08]
 [-0.12]
 [ 0.3 ]] (4, 1)
out:
 [[0]
 [0]
 [0]
 [1]]
error:
 [[0.5 ]
 [0.08]
 [0.12]
 [0.7 ]]


# 퍼셉트론의 구현 (델타룰로 학습 수행)

In [37]:
def stepfunc(x):
    return  (x>=0.0).astype(float) 

In [38]:
class Perceptron:
    def __init__(self, x, y):
        self.input  = x
        self.w      = np.random.random((self.input.shape[1],1))       
        self.t      = y
        self.output = np.zeros_like(self.t) 

    def feedforward(self):
        self.output =  stepfunc(np.dot(self.input, self.w))

    def train(self, eta):
        o_error =  self.t - self.output
        d_w = eta * np.dot(self.input.T, o_error)
        # update the weights
        self.w +=  d_w
    

In [41]:
# 논리-AND를 수행하는 퍼셉트론 ,
# the third input is for bias
x = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[0],[0],[1]] )

nn = Perceptron( x,y )

for i in range(1500):
    nn.feedforward()
    nn.train(0.01)

print('output:\n', nn.output)
print('weights:\n',nn.w)

output:
 [[0.]
 [0.]
 [0.]
 [1.]]
weights:
 [[ 0.1490287 ]
 [ 0.20596199]
 [-0.21473938]]


In [42]:
# 논리-OR를 수행하는 퍼셉트론

x = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[1],[1],[1]] )

nn = Perceptron( x,y )

for i in range(1500):
    nn.feedforward()
    nn.train(0.01)

print('output:\n', nn.output)
print('weights:\n',nn.w)


output:
 [[0.]
 [1.]
 [1.]
 [1.]]
weights:
 [[ 0.78873149]
 [ 0.71336605]
 [-0.00123814]]


In [43]:
# 논리-XOR를 수행하는 퍼셉트론

x = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[1],[1],[0]] )

nn = Perceptron( x,y )

for i in range(1500):
    nn.feedforward()
    nn.train(0.01)

print('output:\n', nn.output)
print('weights:\n',nn.w)

output:
 [[1.]
 [1.]
 [1.]
 [1.]]
weights:
 [[-0.00023221]
 [ 0.00269416]
 [-0.01334462]]
